run:
  timeout: 5m
  skip-dirs-use-default: false
  skip-files:
  - ".*test.go"
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - goheader
    - goimports
    - gofmt
    - govet
    - gosec
    - gosimple
    - misspell
    - ineffassign
    - typecheck
#    - unused
    - whitespace
    - gocyclo
    - nakedret
    - revive

linters-settings:
  goheader:
    template-path: .go-header.txt
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: unused-parameter
        disabled: true
