---
apiVersion: apps.kruise.io/v1alpha1
kind: CloneSet
metadata:
  annotations:
    apps.kruise.io/image-predownload-parallelism: "10"
    apps.kruise.io/image-predownload-min-updated-ready-pods: "3"
  labels:
    app: pangu
  name: pangu
  namespace: pangu
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pangu
  template:
    metadata:
      labels:
        app: pangu
    spec:
      containers:
      - name: pangu
        image: ttl.sh/ysicing/pangu:2023
        imagePullPolicy: Always
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: PGU_DEBUG
          value: "true"
  updateStrategy:
    type: InPlaceIfPossible
    inPlaceUpdateStrategy:
      gracePeriodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: pangu
  labels:
    app: pangu
  namespace: pangu
spec:
  ports:
  - port: 65001
    targetPort: 65001
    protocol: TCP
    name: http
  selector:
    app: pangu

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: pangu
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls
  namespace: pangu
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`pangu.bjslb.ysicing.net`)
    kind: Rule
    services:
    - name: pangu
      port: 65001
    middlewares:
      - name: redirect-https
  tls:
    certResolver: myresolver

