name: build

on:
  push:
    branches:
      - '*'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.D_H }}
          username: ${{ secrets.D_U }}
          password: ${{ secrets.D_P }}
      - name: Build amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          pull: true
          tags: ${{ secrets.D_H }}/ysicing-cloud/pangu:2023
