info:
  contact:
    email: i@ysicing.me
    name: ysicing
    url: http://github.com/ysicing/pangu
  description: pangu.
  license:
    name: AGPLv3
    url: https://opensource.org/licenses/MIT
  title: Pangu API
  version: v0.0.2-20231212-216bca2
paths:
  /api/configs:
    get:
      consumes:
      - application/json
      parameters:
      - description: jwtToken
        in: header
        name: Authorization
        type: string
      - description: staticToken
        in: header
        name: X-Auth-Token
        type: string
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: 获取配置
      tags:
      - config
  /cdn-cgi/trace:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
      summary: CF CDN
      tags:
      - custom
swagger: "2.0"
